### ISSUE TITLE
[ERROR] "Permission denied: '../../../data/views/KuHar/resampled_view_20Hz'" while saving KuHar's 20Hz resampled view 

### ISSUE THREAD

**Issue by joaoppagnan** [otavioon/librep-hiaac#14]
**Describe the bug:**

While saving the KuHar's 20Hz resampled view, the error "Permission denied: '../../../data/views/KuHar/resampled_view_20Hz'" is being returned.

**To Reproduce:**

Run the notebook `notebooks/datasets_views/KuHar_Resampled_20Hz.ipynb` of the **resampled_kuhar_20Hz** branch.

**Expected behavior:**

The resampled dataset should be saved without any errors.

**Desktop:**

OS: Ubuntu 20.04

**Comment by otavioon** [comment]
Hello @joaoppagnan. I have changed the permission of the root folder. Please, try again.

Att.,
Otávio Napoli

**Comment by joaoppagnan** [comment]
Hello, @otavioon. Sadly, the error still happens when I try to save the data :(

Att.,
João Pagnan

**Comment by otavioon** [comment]
It was resolved. Please try again.
